### ISSUE TITLE
Unused arguments in `DocumentFile.getContent`

### ISSUE THREAD

**Issue by clragon** [alexrintt/shared-storage#107]
**Describe the bug**
Both `DocumentFile.getContent` and `DocumentFile.getContentAsString` demand a parameter called `Uri destination`.
It is unclear to me why this parameter is needed and it is entirely unused in the code.

**Expected behavior**
I would assume that neither of those functions would take a parameter, as their location is already available in the properties of the `DocumentFile` itself.

**shared_storage:**
 - Version 0.5.0

**Comment by alexrintt** [comment]
You're right, for now you can use:

```dart
// Workaround <= 0.5.0
uri.getContentAsString(uri);
```

And since it's a breaking change, I'll add release a fix in the next major version **v0.6.0**.

Thanks for the issue.

**Comment by alexrintt** [comment]
`v0.6.0` published available at pub.dev: [pub.dev/packages/shared_storage](https://pub.dev/packages/shared_storage).

**Comment by clragon** [comment]
thank you!
