### ISSUE TITLE
Losing access to folder contents after device reboot

### ISSUE THREAD

**Issue by Tamerlanchiques** [alexrintt/shared-storage#118]
Hi!

My case is in-app music player. User opens some directories (openDocumentTree) and watch music content in the app UI.

All works fine till device reboot. After reboot I see list of persisted folders (persistedUriPermissions) but when I trying to access contents of folder I get "No permission granted" error. Ask user for granting permissions each time is not user friendly and I looking for solution on this issue. 

Watched your [example app](https://github.com/alexrintt/shared-storage/tree/master/example) but seen same problem there: list of persisted uris and no permission on reading contents each device reboot.

https://user-images.githubusercontent.com/11006352/230379868-5f16f3a9-af1b-47b0-a6e5-76438f428cdc.mp4

_Quick demo of problem._

After some research I found that we need [strictly specify that we need grant access across device reboots ](https://developer.android.com/reference/android/content/Intent.html#FLAG_GRANT_PERSISTABLE_URI_PERMISSION). As I can see [your openDocumentTree](https://github.com/alexrintt/shared-storage/blob/master/lib/src/saf/saf.dart#L23) function has parameter 'persistablePermission' that looks like granting permissions across reboots is default behaviour but seems not work.

So… what can I do for granting folder contents read permissions device across reboots?

**Comment by Tamerlanchiques** [comment]
Emulator Android version on the related video demo is Android Q (10), 29 API level.

**Comment by alexrintt** [comment]
Already fixed, I'll be pushing a new version 0.7.1 to fix this behavior in a few hours. Thank you very much for your detailed issue, this is a huge help on bug reports.

**Comment by alexrintt** [comment]
Welcome to the club :)

**Comment by alexrintt** [comment]
Released 0.7.1, please, run flutter pub get to update the version, or explicitly set (recommended):

```yaml
dependencies:
  # ...
  shared_storage: ^0.7.1
```

I'll close this issue, but if this same issue persists feel free to re-open. You can also see the fix [here](https://github.com/alexrintt/shared-storage/pull/119/files).
