### ISSUE TITLE
openDocumentFile() returns null

### ISSUE THREAD

**Issue by mx1up** [alexrintt/shared-storage#121]
**Describe the bug**
documentFile.openDocumentFile returns null, even on success

**To Reproduce**
final result = await documentFile.openDocumentFile()

**Expected behavior**
result to be true on success

**Smartphone (please complete the following information):**
 - Device: android emulator 
 - OS: android api 33
 - Version 0.7.1

**Additional context**
this problem is reproducable using the sample app: example/lib/utils/document_file_utils.dart:25
`launched` is null on successful launch

**Comment by alexrintt** [comment]
Fix was released under v0.7.2, please re-open the issue if this behavior persists.

**Comment by alexrintt** [comment]
Seems good, I'll provide this as part of v8 since it's a breaking change. Would be helpful if you could provide any exceptions you would like to handle, for now I can think only on **Activity not found**, **Security Exception** (when no read permission) and **Unknown**.

**Comment by mx1up** [comment]
cool, the exceptions you listed are indeed the important ones, of which **Activity not found** would be the most common in my use case. 

btw, in theory, I think 0.7.2 introduced a breaking change, not on api signature level, but on behavioral level, by not throwing exceptions anymore in cases where an exception was expected.

**Comment by alexrintt** [comment]
Think you are right. I was using signature level as metric for breaking vs minor changes. 

Not sure how an app would get a exception from these changes though, who was handling exceptions + the boolean return value doesn't need to change anything, in last case the client will just ignore the exception (since it doesn't throw anything now), but anyway thanks for the warning, I'll take better care from now on.

**Comment by alexrintt** [comment]
Retracted version 0.7.2, since it was released only 8h ago, I think there are only few affected clients besides you, I'll release the fix of this issue at v8.

**Comment by mx1up** [comment]
great, sorry for all the hassle ;)

**Comment by alexrintt** [comment]
I'll add an API method `tryOpenDocumentFile`, it will return a `Future<void>` and will throw any errors with type and details. 

The current openDocumentFile will be a simple `try { true } catch { false }` around this new method.

This let the old users migrate to the fixed `openDocumentFile` and let people implement custom catches if they want to, using the new `tryOpenDocumentFile`.

Gonna add details soon.

**Comment by alexrintt** [comment]
Launched `openDocumentFileWithResult` at v.0.8, see [ref](https://alexrintt.io/shared-storage/Usage/Storage%20Access%20Framework/#opendocumentfilewithresult).

I'll mark as done but feel free to re-open if needed.
