### ISSUE TITLE
Build fails on latest flutter beta

### ISSUE THREAD

**Issue by Persie0** [alexrintt/shared-storage#150]
**Describe the bug**
When building an appbundle on the latest flutter beta, you get an error. Stable works fine.

**To Reproduce**
Run flutter build appbundle --obfuscate --split-debug-info=./build
`Running Gradle task 'bundleRelease'...     
                     
...

warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: Recompile with -Xlint:deprecation for details.
3 warnings
/opt/hostedtoolcache/flutter/3.19.0-0.1.pre-beta/x64/.pub-cache/hosted/pub.dev/shared_storage-0.8.0/lib/src/common/functional_extender.dart:28:36: Error: A value of type 'Object?' can't be returned from a function with return type 'T?'.
 - 'Object' is from 'dart:core'.
    return self != null && f(self) ? self : null;
                                   ^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/opt/hostedtoolcache/flutter/3.19.0-0.1.pre-beta/x64/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 34s
Running Gradle task 'bundleRelease'...                            [27](https://github.com/Persie0/r/actions/runs/7515477589/job/20459430990#step:6:28)5.3s
Gradle task bundleRelease failed with exit code 1
Error: Process completed with exit code 1.`

**Comment by Persie0** [comment]
now also on latest stable, any update?


3 warnings
/opt/hostedtoolcache/flutter/3.19.0-stable/x64/.pub-cache/hosted/pub.dev/shared_storage-0.8.0/lib/src/common/functional_extender.dart:28:36: Error: A value of type 'Object?' can't be returned from a function with return type 'T?'.
 - 'Object' is from 'dart:core'.
    return self != null && f(self) ? self : null;
                                   ^
Target kernel_snapshot failed: Exception

**Comment by alexcmgit** [comment]
Thanks for reporting, published a fix https://pub.dev/packages/shared_storage/versions/0.8.1.
